Repository fedspendingtransparency/data-act-build-tools, pull requests merged in 2022-07, with the labels that each got.

#304 remove worker and node type params
  databricks/cluster_config.py
Labels: Ready for Review, Work In Progress

#303 ops-2298 Add support for GTAS failed edits
  pull_and_rename_cars_gtas.py
Labels: Work In Progress

#309 run_dbr argparse
  databricks/cluster_config.py
  databricks/run_databricks_jobs.py
Labels: Ready for Review

#311 change debug and wait parameters to boolean switches
  databricks/run_databricks_jobs.py
Labels: Ready for Review
